version: "3.8"

services: 
  api:
    image: thoughtful
    container_name: thoughtful
    build:
      context: .
      dockerfile: Dockerfile-local
    ports: 
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env