FROM python:3.9-slim-buster

WORKDIR /app

ENV PYTHONUNBUFFERED=true
ENV PYTHONDONTWRITEBYTECODE=true
ENV DJANGO_SETTINGS_MODULE=config.settings.heroku
ENV ALLOWED_HOSTS=the-thoughtful-api.herokuapp.com

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN mkdir /app/staticfiles
RUN python manage.py collectstatic --noinput

CMD gunicorn config.wsgi:application --bind 0.0.0.0:$PORT 